"""Credential Vault - Encrypted credential storage and management."""

from __future__ import annotations

import base64
import hashlib
import json
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import structlog

logger = structlog.get_logger()


class CredentialVault:
    """
    Secure credential storage using encryption at rest.

    Features:
    - AES-like encryption using Fernet (from cryptography library)
    - Falls back to base64 obfuscation if cryptography not installed
    - Credential rotation tracking
    - Access audit logging
    - Integration with ai.env file

    Note: For a development tool, this provides reasonable security.
    Production deployment should use a proper secrets manager (Vault, AWS SM, etc.)
    """

    def __init__(
        self,
        vault_path: str = ".jeph2sworm/vault.enc",
        key_path: str = ".jeph2sworm/vault.key",
    ):
        self.vault_path = Path(vault_path)
        self.key_path = Path(key_path)
        self._credentials: Dict[str, Dict[str, Any]] = {}
        self._access_log: List[Dict[str, Any]] = []
        self._fernet = None

        self._init_encryption()

    def _init_encryption(self) -> None:
        """Initialize encryption key and Fernet instance."""
        try:
            from cryptography.fernet import Fernet

            if self.key_path.exists():
                key = self.key_path.read_bytes()
            else:
                key = Fernet.generate_key()
                self.key_path.parent.mkdir(parents=True, exist_ok=True)
                self.key_path.write_bytes(key)
                # Restrict permissions
                os.chmod(str(self.key_path), 0o600)

            self._fernet = Fernet(key)
            logger.info("vault_encryption_enabled")

        except ImportError:
            logger.warning("cryptography_not_installed", msg="Vault using base64 fallback")

    def store(
        self,
        name: str,
        value: str,
        category: str = "general",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Store a credential securely."""
        self._credentials[name] = {
            "value": self._encrypt(value),
            "category": category,
            "metadata": metadata or {},
            "created_at": time.time(),
            "rotated_at": time.time(),
            "rotation_count": 0,
        }
        self._persist()
        self._log_access("store", name, "system")
        logger.info("credential_stored", name=name, category=category)

    def retrieve(self, name: str, agent: str = "system") -> Optional[str]:
        """Retrieve a credential value."""
        cred = self._credentials.get(name)
        if not cred:
            return None

        self._log_access("retrieve", name, agent)
        return self._decrypt(cred["value"])

    def rotate(self, name: str, new_value: str) -> bool:
        """Rotate a credential to a new value."""
        cred = self._credentials.get(name)
        if not cred:
            return False

        cred["value"] = self._encrypt(new_value)
        cred["rotated_at"] = time.time()
        cred["rotation_count"] = cred.get("rotation_count", 0) + 1

        self._persist()
        self._log_access("rotate", name, "system")
        logger.info("credential_rotated", name=name, count=cred["rotation_count"])
        return True

    def delete(self, name: str) -> bool:
        """Remove a credential from the vault."""
        if name in self._credentials:
            del self._credentials[name]
            self._persist()
            self._log_access("delete", name, "system")
            return True
        return False

    def list_credentials(self) -> List[Dict[str, Any]]:
        """List all credentials (without values)."""
        result = []
        for name, cred in self._credentials.items():
            result.append({
                "name": name,
                "category": cred.get("category", "general"),
                "created_at": cred.get("created_at"),
                "rotated_at": cred.get("rotated_at"),
                "rotation_count": cred.get("rotation_count", 0),
            })
        return result

    def has(self, name: str) -> bool:
        """Check if a credential exists."""
        return name in self._credentials

    def get_access_log(self, limit: int = 100) -> List[Dict[str, Any]]:
        """Get credential access audit log."""
        return self._access_log[-limit:]

    def export_to_env(self, env_path: str = "ai.env") -> int:
        """Export credentials to an .env file (for deployment use)."""
        lines = ["# Auto-generated by jeph2sworm Credential Vault", ""]
        count = 0

        for name, cred in self._credentials.items():
            value = self._decrypt(cred["value"])
            if value:
                env_key = name.upper().replace("-", "_").replace(".", "_")
                lines.append(f"{env_key}={value}")
                count += 1

        Path(env_path).write_text("\n".join(lines) + "\n")
        os.chmod(env_path, 0o600)

        logger.info("credentials_exported", path=env_path, count=count)
        return count

    def _encrypt(self, plaintext: str) -> str:
        """Encrypt a string."""
        if self._fernet:
            return self._fernet.encrypt(plaintext.encode()).decode()
        else:
            # Base64 fallback (NOT secure, just obfuscation)
            return base64.b64encode(plaintext.encode()).decode()

    def _decrypt(self, ciphertext: str) -> str:
        """Decrypt a string."""
        try:
            if self._fernet:
                return self._fernet.decrypt(ciphertext.encode()).decode()
            else:
                return base64.b64decode(ciphertext.encode()).decode()
        except Exception as e:
            logger.error("decrypt_failed", error=str(e))
            return ""

    def _persist(self) -> None:
        """Save vault to disk (encrypted)."""
        try:
            self.vault_path.parent.mkdir(parents=True, exist_ok=True)
            data = json.dumps(self._credentials, default=str)
            encrypted = self._encrypt(data)
            self.vault_path.write_text(encrypted)
            os.chmod(str(self.vault_path), 0o600)
        except Exception as e:
            logger.error("vault_persist_failed", error=str(e))

    def load(self) -> None:
        """Load vault from disk."""
        if not self.vault_path.exists():
            return

        try:
            encrypted = self.vault_path.read_text()
            data = self._decrypt(encrypted)
            self._credentials = json.loads(data)
            logger.info("vault_loaded", credentials=len(self._credentials))
        except Exception as e:
            logger.error("vault_load_failed", error=str(e))

    def _log_access(self, action: str, credential: str, agent: str) -> None:
        """Log a credential access event."""
        self._access_log.append({
            "action": action,
            "credential": credential,
            "agent": agent,
            "timestamp": time.time(),
        })

        # Keep bounded
        if len(self._access_log) > 5000:
            self._access_log = self._access_log[-2500:]
