"""
AI Environment Manager — manages the ai.env file for the project.
Handles creation, reading, updating, rotation, and export of credentials.
Separate from credential_generator to provide project-level env management.
"""

from __future__ import annotations

import os
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional

from jeph2sworm.tools.credential_generator import CredentialGenerator


class AiEnvManager:
    """Manages the ai.env file for a project workspace."""

    ENV_FILENAME = "ai.env"
    GITIGNORE_ENTRY = "ai.env"

    HEADER_TEMPLATE = """\
# ================================================
# ai.env — Auto-generated by Jeph2Sworm
# ================================================
# WARNING: This file contains sensitive credentials
# DO NOT commit to version control
# ================================================
# Generated: {timestamp}
# Project: {project_name}
# ================================================
"""

    def __init__(self, workspace_dir: str) -> None:
        self.workspace_dir = Path(workspace_dir)
        self.env_path = self.workspace_dir / self.ENV_FILENAME
        self.generator = CredentialGenerator()

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def initialize(self, project_name: str = "jeph2sworm-project") -> Path:
        """Create ai.env with header if it doesn't exist and ensure .gitignore has it."""
        if not self.env_path.exists():
            header = self.HEADER_TEMPLATE.format(
                timestamp=datetime.utcnow().isoformat(),
                project_name=project_name,
            )
            self.env_path.write_text(header)
            self.env_path.chmod(0o600)

        self._ensure_gitignore()
        return self.env_path

    def read_all(self) -> dict[str, str]:
        """Parse ai.env and return key-value dict."""
        result: dict[str, str] = {}
        if not self.env_path.exists():
            return result
        for line in self.env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)", line)
            if match:
                key = match.group(1)
                value = match.group(2).strip().strip("\"'")
                result[key] = value
        return result

    def get(self, key: str) -> Optional[str]:
        return self.read_all().get(key)

    def set(self, key: str, value: str, comment: str = "") -> None:
        """Set or update a key in ai.env."""
        entries = self._read_raw_lines()
        found = False
        for i, line in enumerate(entries):
            if line.strip().startswith(f"{key}="):
                entries[i] = f'{key}="{value}"'
                found = True
                break
        if not found:
            if comment:
                entries.append(f"\n# {comment}")
            entries.append(f'{key}="{value}"')

        self.env_path.write_text("\n".join(entries) + "\n")

    def generate_and_set(
        self, key: str, length: int = 32, comment: str = ""
    ) -> str:
        """Generate a secure credential and store it."""
        password = self.generator.generate_password(length)
        self.set(key, password, comment)
        return password

    def remove(self, key: str) -> bool:
        """Remove a key from ai.env."""
        lines = self._read_raw_lines()
        new_lines = [l for l in lines if not l.strip().startswith(f"{key}=")]
        if len(new_lines) == len(lines):
            return False
        self.env_path.write_text("\n".join(new_lines) + "\n")
        return True

    def rotate_all(self) -> dict[str, str]:
        """Regenerate all credentials in ai.env."""
        current = self.read_all()
        backup_path = self._backup()
        new_creds: dict[str, str] = {}
        for key in current:
            new_val = self.generator.generate_password(max(32, len(current[key])))
            self.set(key, new_val)
            new_creds[key] = new_val
        return new_creds

    def export_for_shell(self) -> str:
        """Export all entries as shell export commands."""
        entries = self.read_all()
        return "\n".join(f'export {k}="{v}"' for k, v in entries.items())

    def export_for_docker(self) -> str:
        """Export as Docker --env-file compatible format (no quotes)."""
        entries = self.read_all()
        return "\n".join(f"{k}={v}" for k, v in entries.items())

    def list_keys(self) -> list[str]:
        return list(self.read_all().keys())

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _read_raw_lines(self) -> list[str]:
        if not self.env_path.exists():
            return []
        return self.env_path.read_text().splitlines()

    def _backup(self) -> Path:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        backup = self.env_path.with_name(f"ai.env.backup.{ts}")
        shutil.copy2(self.env_path, backup)
        return backup

    def _ensure_gitignore(self) -> None:
        gitignore = self.workspace_dir / ".gitignore"
        if gitignore.exists():
            content = gitignore.read_text()
            if self.GITIGNORE_ENTRY not in content:
                with gitignore.open("a") as f:
                    f.write(f"\n{self.GITIGNORE_ENTRY}\n")
        else:
            gitignore.write_text(f"{self.GITIGNORE_ENTRY}\n")
