"""Secure credential generator and ai.env manager."""

from __future__ import annotations

import secrets
import string
from pathlib import Path
from typing import Optional

import aiofiles
import structlog

from jeph2sworm.security.rules_engine import RulesEngine

logger = structlog.get_logger()


class CredentialGenerator:
    """Generate cryptographically secure passwords with 128-bit+ entropy."""

    # Character sets for password generation
    UPPERCASE = string.ascii_uppercase
    LOWERCASE = string.ascii_lowercase
    DIGITS = string.digits
    SYMBOLS = "!@#$%^&*()-_=+[]{}|;:,.<>?"

    @staticmethod
    def generate_password(length: int = 32) -> str:
        """
        Generate a secure password.

        Requirements:
        - Minimum 32 characters
        - Contains uppercase, lowercase, digits, symbols
        - 128-bit+ entropy
        - No dictionary words, no sequential chars, no repeated patterns
        """
        if length < 32:
            length = 32

        all_chars = (
            CredentialGenerator.UPPERCASE
            + CredentialGenerator.LOWERCASE
            + CredentialGenerator.DIGITS
            + CredentialGenerator.SYMBOLS
        )

        while True:
            # Generate password
            password = "".join(secrets.choice(all_chars) for _ in range(length))

            # Verify it meets all requirements
            has_upper = any(c in CredentialGenerator.UPPERCASE for c in password)
            has_lower = any(c in CredentialGenerator.LOWERCASE for c in password)
            has_digit = any(c in CredentialGenerator.DIGITS for c in password)
            has_symbol = any(c in CredentialGenerator.SYMBOLS for c in password)

            if all([has_upper, has_lower, has_digit, has_symbol]):
                # Check no 3+ sequential identical chars
                has_repeat = any(
                    password[i] == password[i + 1] == password[i + 2]
                    for i in range(len(password) - 2)
                )
                if not has_repeat:
                    return password

    @staticmethod
    def generate_secret(length: int = 64) -> str:
        """Generate a hex-encoded secret (for JWT, session, etc.)."""
        return secrets.token_hex(length // 2)


class AiEnvManager:
    """
    Manages the ai.env file — the secure credential store for the project.

    Creates, reads, updates ai.env. Ensures passwords meet security standards.
    Auto-adds ai.env to .gitignore.
    """

    HEADER = """# ================================================
# ai.env -- Auto-generated by Jeph2Sworm
# ================================================
# WARNING: This file contains sensitive credentials
# DO NOT commit to version control
# ================================================

"""

    def __init__(self, workspace_root: Path, rules: RulesEngine) -> None:
        self.workspace_root = workspace_root
        self.rules = rules
        self.env_path = workspace_root / "ai.env"
        self._credentials: dict[str, str] = {}

    async def initialize(self) -> None:
        """Create ai.env and add to .gitignore."""
        if not self.env_path.exists():
            async with aiofiles.open(self.env_path, "w") as f:
                await f.write(self.HEADER)
            await logger.ainfo("ai_env_created", path=str(self.env_path))

        # Ensure ai.env is in .gitignore
        gitignore_path = self.workspace_root / ".gitignore"
        gitignore_content = ""
        if gitignore_path.exists():
            async with aiofiles.open(gitignore_path, "r") as f:
                gitignore_content = await f.read()

        if "ai.env" not in gitignore_content:
            async with aiofiles.open(gitignore_path, "a") as f:
                await f.write("\n# Jeph2Sworm credentials\nai.env\n")
            await logger.ainfo("ai_env_added_to_gitignore")

        # Load existing credentials
        await self._load()

    async def set_credential(
        self,
        key: str,
        value: Optional[str] = None,
        comment: Optional[str] = None,
        auto_generate: bool = False,
        agent_id: str = "system",
    ) -> str:
        """
        Set a credential in ai.env.

        If auto_generate=True, a secure password is generated.
        Returns the credential value.
        """
        if auto_generate:
            if "SECRET" in key or "TOKEN" in key:
                value = CredentialGenerator.generate_secret()
            else:
                value = CredentialGenerator.generate_password()

        if not value:
            raise ValueError(f"No value provided for credential: {key}")

        # Validate password strength for password-type keys
        password_keys = ["PASSWORD", "SECRET", "TOKEN", "KEY"]
        if any(pk in key.upper() for pk in password_keys):
            self.rules.validate_password_strength(value)

        self._credentials[key] = value
        await self._save()

        await logger.ainfo("credential_set", key=key, agent=agent_id)
        return value

    async def get_credential(self, key: str) -> Optional[str]:
        """Get a credential value."""
        return self._credentials.get(key)

    async def list_credentials(self, masked: bool = True) -> list[dict]:
        """List all credentials, optionally masked."""
        result = []
        for key, value in self._credentials.items():
            result.append({
                "key": key,
                "value": value[:4] + "*" * (len(value) - 4) if masked and len(value) > 4 else value,
                "length": len(value),
            })
        return result

    async def rotate_all(self, agent_id: str = "system") -> int:
        """Regenerate all password-type credentials."""
        count = 0
        password_keys = ["PASSWORD", "SECRET", "TOKEN"]
        for key in list(self._credentials.keys()):
            if any(pk in key.upper() for pk in password_keys):
                await self.set_credential(key, auto_generate=True, agent_id=agent_id)
                count += 1
        return count

    async def export_for_deployment(self) -> str:
        """Export credentials in .env format for deployment."""
        lines = []
        for key, value in self._credentials.items():
            lines.append(f"{key}={value}")
        return "\n".join(lines)

    # ---- Private ----

    async def _load(self) -> None:
        """Load credentials from ai.env file."""
        if not self.env_path.exists():
            return

        async with aiofiles.open(self.env_path, "r") as f:
            content = await f.read()

        for line in content.splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                self._credentials[key.strip()] = value.strip()

    async def _save(self) -> None:
        """Save credentials to ai.env file."""
        lines = [self.HEADER]
        for key, value in self._credentials.items():
            lines.append(f"{key}={value}")
        lines.append("")

        async with aiofiles.open(self.env_path, "w") as f:
            await f.write("\n".join(lines))
