/**
 * Credential Manager — generates secure credentials and manages ai.env.
 * Client-side counterpart of Python credential_generator.py.
 */

import * as vscode from 'vscode';
import * as crypto from 'crypto';
import * as path from 'path';

const CHARSET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+[]{}|;:,.<>?';

export class CredentialManager {
  private workspaceRoot: string;
  private envFilePath: string;

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot;
    this.envFilePath = path.join(workspaceRoot, 'ai.env');
  }

  generatePassword(length = 32): string {
    const bytes = crypto.randomBytes(length);
    return Array.from(bytes)
      .map(b => CHARSET[b % CHARSET.length])
      .join('');
  }

  generateSecret(length = 64): string {
    return crypto.randomBytes(length).toString('hex');
  }

  async readEnvFile(): Promise<Map<string, string>> {
    const map = new Map<string, string>();
    try {
      const content = Buffer.from(
        await vscode.workspace.fs.readFile(vscode.Uri.file(this.envFilePath))
      ).toString('utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) { continue; }
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx > 0) {
          const key = trimmed.substring(0, eqIdx).trim();
          let value = trimmed.substring(eqIdx + 1).trim();
          if ((value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
          }
          map.set(key, value);
        }
      }
    } catch {
      // File doesn't exist
    }
    return map;
  }

  async writeEnvVar(key: string, value: string): Promise<void> {
    const envMap = await this.readEnvFile();
    envMap.set(key, value);
    const lines = ['# Generated by jeph2sworm — DO NOT COMMIT', ''];
    for (const [k, v] of envMap) {
      lines.push(`${k}="${v}"`);
    }
    await vscode.workspace.fs.writeFile(
      vscode.Uri.file(this.envFilePath),
      Buffer.from(lines.join('\n') + '\n', 'utf-8')
    );
  }

  async generateAndStore(key: string, length = 32): Promise<string> {
    const password = this.generatePassword(length);
    await this.writeEnvVar(key, password);
    return password;
  }

  getEntropy(password: string): number {
    const unique = new Set(password).size;
    return Math.log2(Math.pow(unique, password.length));
  }
}
